# Generated by Django 3.1.2 on 2021-06-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0003_auto_20210608_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_images',
            new_name='item_image',
        ),
    ]
